### ISSUE TITLE
Milestone IP sign off status form doesn't submit

### ISSUE THREAD

**Issue by PangolinPaw** [OE-Development/OE-System#43] opened 2018-01-09 09:22 UTC
The onchange attribute or form ID may be incorrect, as changing the IP status radio buttons doesn't submit any form and so data isn't saved.

![screenshot](https://user-images.githubusercontent.com/9369383/34713574-9ba11ec0-f51e-11e7-8eb2-b464e3a4f3ed.png)

**Comment by decjordan** [comment] 2018-01-09 15:40
Made an amendment to the code and the issue is now fixed

**Closed by decjordan** 2018-01-09 15:40 UTC
Labels: bug, system: digital
